# Generated by Django 2.2 on 2021-12-14 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20211214_1034'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='user1',
        ),
    ]
