# Generated by Django 2.2 on 2021-12-14 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211214_1122'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user1',
            new_name='register',
        ),
    ]
