# Generated by Django 2.2 on 2021-11-08 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20211108_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='avaiable',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.categ'),
        ),
    ]
